import type { Metadata } from "next";
import { Aboreto } from "next/font/google";
import "./globals.css";
import Head from "./Header";

const roboto = Aboreto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Head/>
        {children}</body>
    </html>
  );
}
